[package]
name = "gba-uart-echo"
version = "0.1.0"
authors = ["Michael Mogenson <michael.mogenson@gmail.com>"]
edition = "2018"

[dependencies]
panic-abort = "0.3.2"
gba = { git = "https://github.com/rust-console/gba"}
gba-proc-macro = "0.6.0"
voladdress = "0.3.0"
